[package]
name = "kv-sql"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
kv-common = { path = "../kv-common" }
kv-storage = { path = "../kv-storage" }
kv-txn = { path = "../kv-txn" }
async-trait.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
